[package]
name = "talot"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.1"
env_logger = "0.10.1"
log = "0.4.20"
rand = "0.8.5"
rand_distr = "0.4.3"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
