[[categories]]
id = 0
name = "Education"

[[categories]]
id = 1
name = "Work"

[[categories]]
id = 2
name = "Entertainment"

[[categories]]
id = 3
name = "Relationships"

[[categories]]
id = 4
name = "Fitness"

[[categories]]
id = 5
name = "Travel"

[[categories]]
id = 6
name = "Health"

[[categories]]
id = 7
name = "Hobbies"

[[categories]]
id = 8
name = "Personal Development"

[[categories]]
id = 9
name = "Finance"

[[categories]]
id = 10
name = "Spirituality"

[[lots.0]]
desc = "Graduate from high school"
p = 0.1
[[lots.0]]
desc = "Get a bachelor's degree"
p = 0.2
[[lots.0]]
desc = "Attend a professional training"
p = 0.15
[[lots.0]]
desc = "Learn a new language"
p = 0.1
[[lots.0]]
desc = "Take an online course"
p = 0.15
[[lots.0]]
desc = "Read a textbook"
p = 0.1
[[lots.0]]
desc = "Write a research paper"
p = 0.05
[[lots.0]]
desc = "Attend a seminar"
p = 0.05
[[lots.0]]
desc = "Participate in a study group"
p = 0.05
[[lots.0]]
desc = "Complete a project"
p = 0.05

[[lots.1]]
desc = "Start a new job"
p = 0.1
[[lots.1]]
desc = "Get a promotion"
p = 0.15
[[lots.1]]
desc = "Change career paths"
p = 0.1
[[lots.1]]
desc = "Attend a work conference"
p = 0.1
[[lots.1]]
desc = "Complete a major project"
p = 0.15
[[lots.1]]
desc = "Receive a bonus"
p = 0.1
[[lots.1]]
desc = "Meet a work deadline"
p = 0.1
[[lots.1]]
desc = "Learn a new work skill"
p = 0.1
[[lots.1]]
desc = "Receive positive feedback"
p = 0.05
[[lots.1]]
desc = "Achieve a work goal"
p = 0.05

[[lots.2]]
desc = "Watch a movie"
p = 0.15
[[lots.2]]
desc = "Go to a concert"
p = 0.1
[[lots.2]]
desc = "Play a video game"
p = 0.15
[[lots.2]]
desc = "Read a novel"
p = 0.1
[[lots.2]]
desc = "Listen to a new album"
p = 0.1
[[lots.2]]
desc = "Visit a museum"
p = 0.1
[[lots.2]]
desc = "Go to a party"
p = 0.1
[[lots.2]]
desc = "Attend a sports event"
p = 0.1
[[lots.2]]
desc = "Go on a trip"
p = 0.05
[[lots.2]]
desc = "Try a new hobby"
p = 0.05

[[lots.3]]
desc = "Start a new relationship"
p = 0.1
[[lots.3]]
desc = "Go on a first date"
p = 0.15
[[lots.3]]
desc = "Get married"
p = 0.1
[[lots.3]]
desc = "Have a child"
p = 0.1
[[lots.3]]
desc = "Celebrate an anniversary"
p = 0.1
[[lots.3]]
desc = "Meet the parents"
p = 0.1
[[lots.3]]
desc = "Move in together"
p = 0.1
[[lots.3]]
desc = "Have a disagreement"
p = 0.1
[[lots.3]]
desc = "Make up after a fight"
p = 0.05
[[lots.3]]
desc = "Go on a romantic getaway"
p = 0.05

[[lots.4]]
desc = "Start a new workout routine"
p = 0.1
[[lots.4]]
desc = "Run a marathon"
p = 0.1
[[lots.4]]
desc = "Lift a personal best"
p = 0.15
[[lots.4]]
desc = "Try a new sport"
p = 0.1
[[lots.4]]
desc = "Join a gym"
p = 0.1
[[lots.4]]
desc = "Take a yoga class"
p = 0.1
[[lots.4]]
desc = "Go for a swim"
p = 0.1
[[lots.4]]
desc = "Climb a mountain"
p = 0.1
[[lots.4]]
desc = "Learn a new dance"
p = 0.05
[[lots.4]]
desc = "Achieve a fitness goal"
p = 0.05

[[lots.5]]
desc = "Visit a new country"
p = 0.1
[[lots.5]]
desc = "Go on a road trip"
p = 0.15
[[lots.5]]
desc = "Try a new cuisine"
p = 0.1
[[lots.5]]
desc = "Learn about a new culture"
p = 0.1
[[lots.5]]
desc = "Go camping"
p = 0.1
[[lots.5]]
desc = "Take a cruise"
p = 0.1
[[lots.5]]
desc = "Visit a famous landmark"
p = 0.1
[[lots.5]]
desc = "Go on a safari"
p = 0.1
[[lots.5]]
desc = "Take a hiking trip"
p = 0.05
[[lots.5]]
desc = "Go on a beach vacation"
p = 0.05

[[lots.6]]
desc = "Get a check-up"
p = 0.1
[[lots.6]]
desc = "Recover from an illness"
p = 0.15
[[lots.6]]
desc = "Start a new diet"
p = 0.1
[[lots.6]]
desc = "Quit a bad habit"
p = 0.1
[[lots.6]]
desc = "Get a vaccination"
p = 0.1
[[lots.6]]
desc = "Start a meditation practice"
p = 0.1
[[lots.6]]
desc = "Get enough sleep"
p = 0.1
[[lots.6]]
desc = "Drink enough water"
p = 0.1
[[lots.6]]
desc = "Eat a balanced meal"
p = 0.05
[[lots.6]]
desc = "Achieve a health goal"
p = 0.05

[[lots.7]]
desc = "Start a new hobby"
p = 0.1
[[lots.7]]
desc = "Master a skill"
p = 0.15
[[lots.7]]
desc = "Join a club"
p = 0.1
[[lots.7]]
desc = "Complete a project"
p = 0.1
[[lots.7]]
desc = "Learn to play a musical instrument"
p = 0.1
[[lots.7]]
desc = "Start a collection"
p = 0.1
[[lots.7]]
desc = "Read a book"
p = 0.1
[[lots.7]]
desc = "Write a story"
p = 0.1
[[lots.7]]
desc = "Paint a picture"
p = 0.05
[[lots.7]]
desc = "Take a photography trip"
p = 0.05

[[lots.8]]
desc = "Set a personal goal"
p = 0.1
[[lots.8]]
desc = "Achieve a personal goal"
p = 0.15
[[lots.8]]
desc = "Learn a new skill"
p = 0.1
[[lots.8]]
desc = "Overcome a fear"
p = 0.1
[[lots.8]]
desc = "Start a journal"
p = 0.1
[[lots.8]]
desc = "Read a self-help book"
p = 0.1
[[lots.8]]
desc = "Take a personal development course"
p = 0.1
[[lots.8]]
desc = "Practice mindfulness"
p = 0.1
[[lots.8]]
desc = "Improve a relationship"
p = 0.05
[[lots.8]]
desc = "Develop a positive habit"
p = 0.05

[[lots.9]]
desc = "Save money"
p = 0.1
[[lots.9]]
desc = "Invest in stocks"
p = 0.15
[[lots.9]]
desc = "Buy a house"
p = 0.1
[[lots.9]]
desc = "Start a business"
p = 0.1
[[lots.9]]
desc = "Pay off a debt"
p = 0.1
[[lots.9]]
desc = "Create a budget"
p = 0.1
[[lots.9]]
desc = "Increase income"
p = 0.1
[[lots.9]]
desc = "Donate to charity"
p = 0.1
[[lots.9]]
desc = "Plan for retirement"
p = 0.05
[[lots.9]]
desc = "Achieve a financial goal"
p = 0.05

[[lots.10]]
desc = "Start a meditation practice"
p = 0.1
[[lots.10]]
desc = "Read a spiritual book"
p = 0.15
[[lots.10]]
desc = "Visit a place of worship"
p = 0.1
[[lots.10]]
desc = "Join a spiritual group"
p = 0.1
[[lots.10]]
desc = "Practice mindfulness"
p = 0.1
[[lots.10]]
desc = "Attend a spiritual retreat"
p = 0.1
[[lots.10]]
desc = "Learn about different religions"
p = 0.1
[[lots.10]]
desc = "Read religious texts"
p = 0.1
[[lots.10]]
desc = "Practice gratitude"
p = 0.05
[[lots.10]]
desc = "Achieve a spiritual goal"
p = 0.05
